version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BACKEND_PORT}:5000
    volumes:
      - ./backend:/usr/src/app
    environment:
      - MONGO_URL=mongodb://mongo:27017/myapp
    depends_on:
      - mongo
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - ${FRONTEND_PORT}:3000
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - API_URL=http://localhost:5000
    depends_on:
      - backend
  mongo:
    image: mongo:latest
    ports:
     - 27017:27017
    volumes:
     - mongodbdata:/data/db

volumes:
  mongodbdata:

